packages:
  - .

confirmModulesPurge: false
verifyDepsBeforeRun: false

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - koffi

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  koffi: true
